import type { Shift } from "../../types/Shift";

const data: Shift[] = [
  {
    id: "WEB-01",
    name: "Shift LEGO Spider-Man",
    isComplete: true,
    date: "2025-01-01T00:00:00Z",
    description: "The shift of the LEGO Spider-Man Figure Production Line",
    logs: [
      {
        id: "oee",
        label: "oee",
        value: 0.68,
        type: "percentage",
        description: "The overall equipment efficiency in %",
        category: "efficiency",
      },
      {
        id: "sl",
        label: "Speed loss",
        value: -10.5,
        type: "number",
        description: "The line speed loss",
        category: "efficiency",
      },
      {
        id: "lbp",
        label: "Loss before pallets",
        value: -268,
        type: "number",
        description: "Loss of produced goods before reaching the palletizer",
        category: "efficiency",
      },
      {
        id: "cln_shift",
        label: "Cleaning in shift",
        value: 2280,
        type: "secs",
        description:
          "Time spent (in seconds) cleaning the machines during the last shift",
        category: "shift",
      },
      {
        id: "shift_duration",
        label: "Shift duration",
        value: 8,
        type: "hours",
        description: "Last shift duration in hours",
        category: "shift",
      },
      {
        id: "unexplained",
        label: "Unexplained downtime",
        value: 180,
        type: "secs",
        description: "The downtime (in seconds) caused by undocumented reasons",
        category: "downtime",
      },
      {
        id: "mech_problems",
        label: "Mechanical problems",
        value: 1210,
        type: "secs",
        description: "The downtime (in seconds) caused by mechanical problems",
        category: "downtime",
      },
    ],
  },
  {
    id: "GOTHAM",
    name: "Shift LEGO Batman",
    isComplete: true,
    date: "2025-01-02T00:00:00Z",
    description: "The second shift of the LEGO Batman Figure Production Line",
    logs: [
      {
        id: "oee",
        label: "oee",
        value: 0.7,
        type: "percentage",
        description: "The overall equipment efficiency in %",
        category: "efficiency",
      },
      {
        id: "sl",
        label: "Speed loss",
        value: -8,
        type: "number",
        description: "The line speed loss",
        category: "efficiency",
      },
      {
        id: "lbp",
        label: "Loss before pallets",
        value: -200,
        type: "number",
        description: "Loss of produced goods before reaching the palletizer",
        category: "efficiency",
      },
      {
        id: "cln_shift",
        label: "Cleaning in shift",
        value: 1800,
        type: "secs",
        description: "Time spent cleaning the machines during the last shift",
        category: "shift",
      },
      {
        id: "shift_duration",
        label: "Shift duration",
        value: 7,
        type: "hours",
        description: "Last shift duration in hours",
        category: "shift",
      },
      {
        id: "unexplained",
        label: "Unexplained downtime",
        value: 150,
        type: "secs",
        description: "The downtime caused by undocumented reasons",
        category: "downtime",
      },
      {
        id: "mech_problems",
        label: "Mechanical problems",
        value: 900,
        type: "secs",
        description: "The downtime caused by mechanical problems",
        category: "downtime",
      },
    ],
  },
  {
    id: "AMAZON",
    name: "Shift LEGO Wonder Woman",
    isComplete: true,
    date: "2025-01-03T00:00:00Z",
    description:
      "The third shift of the LEGO Wonder Woman Figure Production Line",
    logs: [
      {
        id: "oee",
        label: "oee",
        value: 0.72,
        type: "percentage",
        description: "The overall equipment efficiency in %",
        category: "efficiency",
      },
      {
        id: "sl",
        label: "Speed loss",
        value: -6,
        type: "number",
        description: "The line speed loss",
        category: "efficiency",
      },
      {
        id: "lbp",
        label: "Loss before pallets",
        value: -150,
        type: "number",
        description: "Loss of produced goods before reaching the palletizer",
        category: "efficiency",
      },
      {
        id: "cln_shift",
        label: "Cleaning in shift",
        value: 2000,
        type: "secs",
        description: "Time spent cleaning the machines during the last shift",
        category: "shift",
      },
      {
        id: "shift_duration",
        label: "Shift duration",
        value: 8,
        type: "hours",
        description: "Last shift duration in hours",
        category: "shift",
      },
      {
        id: "unexplained",
        label: "Unexplained downtime",
        value: 120,
        type: "secs",
        description: "The downtime caused by undocumented reasons",
        category: "downtime",
      },
      {
        id: "mech_problems",
        label: "Mechanical problems",
        value: 1100,
        type: "secs",
        description: "The downtime caused by mechanical problems",
        category: "downtime",
      },
    ],
  },
  {
    id: "STARK",
    name: "Shift LEGO Iron Man",
    isComplete: true,
    date: "2025-01-04T00:00:00Z",
    description: "The fourth shift of the LEGO Iron Man Figure Production Line",
    logs: [
      {
        id: "oee",
        label: "oee",
        value: 0.74,
        type: "percentage",
        description: "The overall equipment efficiency in %",
        category: "efficiency",
      },
      {
        id: "sl",
        label: "Speed loss",
        value: -4,
        type: "number",
        description: "The line speed loss",
        category: "efficiency",
      },
      {
        id: "lbp",
        label: "Loss before pallets",
        value: -100,
        type: "number",
        description: "Loss of produced goods before reaching the palletizer",
        category: "efficiency",
      },
      {
        id: "cln_shift",
        label: "Cleaning in shift",
        value: 1500,
        type: "secs",
        description: "Time spent cleaning the machines during the last shift",
        category: "shift",
      },
      {
        id: "shift_duration",
        label: "Shift duration",
        value: 7,
        type: "hours",
        description: "Last shift duration in hours",
        category: "shift",
      },
      {
        id: "unexplained",
        label: "Unexplained downtime",
        value: 90,
        type: "secs",
        description: "The downtime caused by undocumented reasons",
        category: "downtime",
      },
      {
        id: "mech_problems",
        label: "Mechanical problems",
        value: 800,
        type: "secs",
        description: "The downtime caused by mechanical problems",
        category: "downtime",
      },
    ],
  },
  {
    id: "SHIELD",
    name: "Shift LEGO Captain America",
    isComplete: true,
    date: "2025-01-05T00:00:00Z",
    description:
      "The fifth shift of the LEGO Captain America Figure Production Line",
    logs: [
      {
        id: "oee",
        label: "oee",
        value: 0.76,
        type: "percentage",
        description: "The overall equipment efficiency in %",
        category: "efficiency",
      },
      {
        id: "sl",
        label: "Speed loss",
        value: -2,
        type: "number",
        description: "The line speed loss",
        category: "efficiency",
      },
      {
        id: "lbp",
        label: "Loss before pallets",
        value: -50,
        type: "number",
        description: "Loss of produced goods before reaching the palletizer",
        category: "efficiency",
      },
      {
        id: "cln_shift",
        label: "Cleaning in shift",
        value: 1200,
        type: "secs",
        description: "Time spent cleaning the machines during the last shift",
        category: "shift",
      },
      {
        id: "shift_duration",
        label: "Shift duration",
        value: 8,
        type: "hours",
        description: "Last shift duration in hours",
        category: "shift",
      },
      {
        id: "unexplained",
        label: "Unexplained downtime",
        value: 60,
        type: "secs",
        description: "The downtime caused by undocumented reasons",
        category: "downtime",
      },
      {
        id: "mech_problems",
        label: "Mechanical problems",
        value: 700,
        type: "secs",
        description: "The downtime caused by mechanical problems",
        category: "downtime",
      },
    ],
  },
];

export type FactoryAnalyticsData = typeof data;

export default data;
